---
hooks: {}
git:
  changelog: git log --pretty=format:"* %s (%h)" ${latestTag}...HEAD
  requireCleanWorkingDir: true
  requireUpstream: true
  requireCommits: true
  addUntrackedFiles: false
  commit: true
  commitMessage: 'releaseAutomat: release ${version}'
  commitArgs: ''
  tag: true
  tagName: '${version}'
  tagAnnotation: Release ${version}
  tagArgs: ''
  push: true
  pushArgs: '--follow-tags'
  pushRepo: origin
npm:
  publish: false
  publishPath: '.'
  access:
  otp:
github:
  release: false
  releaseName: Release ${version}
  releaseNotes:
  preRelease: false
  draft: false
  tokenRef: GITHUB_TOKEN
  assets:
  host:
  timeout: 0
  proxy:
gitlab:
  release: false
  releaseName: Release ${version}
  releaseNotes:
  tokenRef: GITLAB_TOKEN
  assets:
  origin:
