plugins:
  # - remark-preset-lint-markdown-style-guide
  - remark-frontmatter
  - remark-lint-match-punctuation
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  # - remark-lint-heading-whitespace
  # - remark-lint-no-dead-urls
  # - remark-lint-code
